"use client";
import { useEffect, useState } from "react";
import { Controller, type Control } from "react-hook-form";
import { Autocomplete, Button, Dialog, DialogActions, DialogContent, DialogContentText, DialogTitle, Stack, TextField } from "@mui/material";
import type { TarefaFormData } from "../schemas/tarefa-schema";
import { criarEtiqueta, excluirEtiqueta, listarEtiquetas } from "../services/etiqueta-service";
import type { Etiqueta } from "../types/tarefa";
type Props = { control: Control<TarefaFormData> };
export function SeletorEtiquetas({ control }: Props) {
  const [opcoes, setOpcoes] = useState<Etiqueta[]>([]); const [nova, setNova] = useState(""); const [erro, setErro] = useState<string | null>(null); const [gerenciar, setGerenciar] = useState(false);
  useEffect(() => { listarEtiquetas().then(setOpcoes).catch((causa: unknown) => setErro(causa instanceof Error ? causa.message : "Não foi possível carregar as etiquetas.")); }, []);
  async function criar(nome: string, atual: number[], alterar: (ids: number[]) => void) { if (!nome.trim()) return; try { const etiqueta = await criarEtiqueta(nome); setOpcoes((itens) => [...itens, etiqueta].sort((a, b) => a.nome.localeCompare(b.nome))); alterar([...atual, etiqueta.id]); setNova(""); setErro(null); } catch (causa) { setErro(causa instanceof Error ? causa.message : "Não foi possível criar a etiqueta."); } }
  async function remover(etiqueta: Etiqueta) { if (!window.confirm(`Excluir "${etiqueta.nome}" de todas as tarefas? As tarefas não serão excluídas.`)) return; try { await excluirEtiqueta(etiqueta.id); setOpcoes((itens) => itens.filter((item) => item.id !== etiqueta.id)); setErro(null); } catch (causa) { setErro(causa instanceof Error ? causa.message : "Não foi possível excluir a etiqueta."); } }
  return <><Controller name="etiquetaIds" control={control} render={({ field }) => <Stack spacing={1}><Autocomplete multiple options={opcoes} value={opcoes.filter((opcao) => field.value.includes(opcao.id))} onChange={(_, valores) => field.onChange(valores.map((valor) => valor.id))} getOptionLabel={(opcao) => opcao.nome} isOptionEqualToValue={(a, b) => a.id === b.id} renderInput={(params) => <TextField {...params} label="Etiquetas" helperText="Opcional. Use as etiquetas existentes ou crie uma nova." />} /><Stack direction={{ xs: "column", sm: "row" }} spacing={1}><TextField size="small" label="Nova etiqueta" value={nova} onChange={(evento) => setNova(evento.target.value)} slotProps={{ htmlInput: { maxLength: 50 } }} /><Button variant="outlined" onClick={() => criar(nova, field.value, field.onChange)}>Criar etiqueta</Button><Button variant="text" onClick={() => setGerenciar(true)}>Gerenciar etiquetas</Button></Stack>{erro && <TextField error value={erro} slotProps={{ input: { readOnly: true } }} />}</Stack>} /><Dialog open={gerenciar} onClose={() => setGerenciar(false)} fullWidth maxWidth="xs"><DialogTitle>Gerenciar etiquetas</DialogTitle><DialogContent><DialogContentText sx={{ mb: 2 }}>Excluir uma etiqueta a remove de todas as tarefas, mas não exclui as tarefas.</DialogContentText><Stack spacing={1}>{opcoes.map((etiqueta) => <Stack key={etiqueta.id} direction="row" sx={{ justifyContent: "space-between", alignItems: "center" }}><span>{etiqueta.nome}</span><Button color="error" onClick={() => remover(etiqueta)}>Excluir</Button></Stack>)}</Stack></DialogContent><DialogActions><Button onClick={() => setGerenciar(false)}>Fechar</Button></DialogActions></Dialog></>;
}
