// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinhaPrimeiraAPI.Data;

#nullable disable

namespace MinhaPrimeiraAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260821160025_AdicionarEtiquetas")]
    partial class AdicionarEtiquetas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("MinhaPrimeiraAPI.Models.Etiqueta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("NOME");

                    b.Property<string>("NomeNormalizado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("NOME_NORMALIZADO");

                    b.HasKey("Id");

                    b.HasIndex("NomeNormalizado")
                        .IsUnique();

                    b.ToTable("ETIQUETAS", (string)null);
                });

            modelBuilder.Entity("MinhaPrimeiraAPI.Models.HistoricoTarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Campo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("CAMPO");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("CRIADO_EM");

                    b.Property<int>("TarefaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TAREFA_ID");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("TIPO");

                    b.Property<string>("ValorAnterior")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("VALOR_ANTERIOR");

                    b.Property<string>("ValorNovo")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("VALOR_NOVO");

                    b.HasKey("Id");

                    b.HasIndex("TarefaId", "CriadoEm");

                    b.ToTable("HISTORICO_TAREFAS", (string)null);
                });

            modelBuilder.Entity("MinhaPrimeiraAPI.Models.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<DateTime?>("ConcluidaEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("CONCLUIDA_EM");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("CRIADA_EM");

                    b.Property<DateOnly?>("DataVencimento")
                        .HasColumnType("TEXT")
                        .HasColumnName("DATA_VENCIMENTO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("DESCRICAO");

                    b.Property<DateTime?>("ExcluidaEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("EXCLUIDA_EM");

                    b.Property<DateTime?>("ModificadaEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("MODIFICADA_EM");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("OBSERVACOES");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Media")
                        .HasColumnName("PRIORIDADE");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("SITUACAO");

                    b.Property<DateTime>("SituacaoAlteradaEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("SITUACAO_ALTERADA_EM");

                    b.HasKey("Id");

                    b.ToTable("TAREFAS", (string)null);
                });

            modelBuilder.Entity("TarefaEtiqueta", b =>
                {
                    b.Property<int>("TAREFA_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ETIQUETA_ID")
                        .HasColumnType("INTEGER");

                    b.HasKey("TAREFA_ID", "ETIQUETA_ID");

                    b.HasIndex("ETIQUETA_ID");

                    b.ToTable("TAREFA_ETIQUETA", (string)null);
                });

            modelBuilder.Entity("MinhaPrimeiraAPI.Models.HistoricoTarefa", b =>
                {
                    b.HasOne("MinhaPrimeiraAPI.Models.Tarefa", "Tarefa")
                        .WithMany()
                        .HasForeignKey("TarefaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarefa");
                });

            modelBuilder.Entity("TarefaEtiqueta", b =>
                {
                    b.HasOne("MinhaPrimeiraAPI.Models.Etiqueta", null)
                        .WithMany()
                        .HasForeignKey("ETIQUETA_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinhaPrimeiraAPI.Models.Tarefa", null)
                        .WithMany()
                        .HasForeignKey("TAREFA_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
