// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinhaPrimeiraAPI.Data;

#nullable disable

namespace MinhaPrimeiraAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260715131302_RenomearCodigoParaId")]
    partial class RenomearCodigoParaId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("MinhaPrimeiraAPI.Models.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("DESCRICAO");

                    b.Property<DateTime?>("ExcluidaEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("EXCLUIDA_EM");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("SITUACAO");

                    b.HasKey("Id");

                    b.ToTable("TAREFAS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
