// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinhaPrimeiraAPI.Data;

#nullable disable

namespace MinhaPrimeiraAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("MinhaPrimeiraAPI.Models.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<DateTime?>("ConcluidaEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("CONCLUIDA_EM");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("CRIADA_EM");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("DESCRICAO");

                    b.Property<DateTime?>("ExcluidaEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("EXCLUIDA_EM");

                    b.Property<DateTime?>("ModificadaEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("MODIFICADA_EM");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("SITUACAO");

                    b.Property<DateTime>("SituacaoAlteradaEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("SITUACAO_ALTERADA_EM");

                    b.HasKey("Id");

                    b.ToTable("TAREFAS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
